# Generated by Django 4.2 on 2023-04-13 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DonoControle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('nome_delegado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Risco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('classificacao', models.CharField(choices=[('BA', 'Baixo'), ('ME', 'Médio'), ('AL', 'Alto')], max_length=2)),
                ('fator_risco', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PlanoAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('NI', 'Não iniciado'), ('EA', 'Em andamento'), ('FI', 'Finalizado')], max_length=2)),
                ('prazo_entrega', models.DateField()),
                ('anexo', models.FileField(upload_to='anexos/')),
                ('controle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_management_v2.controle')),
            ],
        ),
        migrations.AddField(
            model_name='controle',
            name='dono',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='risk_management_v2.donocontrole'),
        ),
        migrations.AddField(
            model_name='controle',
            name='riscos',
            field=models.ManyToManyField(to='risk_management_v2.risco'),
        ),
    ]
